# Generated by Django 4.0.2 on 2022-03-09 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_noteparagraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteparagraph',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='notes.note'),
        ),
    ]
